# Site settings
title: QaLesson.com - ready for a change?
email: admin@qalesson.com 
description: is your one time stop shop for career change # > # this means to ignore newlines until "baseurl:"
baseurl: "qalesson.com" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
